apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: PacketMachineTemplate
metadata:
  name: openebs-worker-arm
  namespace: default
spec:
  template:
    spec:
      OS: ubuntu_20_04
      billingCycle: hourly
      machineType: c1.large.arm
      sshKeys:
        - MBP16
      tags: []
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: openebs
    pool: worker-arm
  name: openebs-worker-arm
  namespace: default
spec:
  clusterName: openebs
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: openebs
      pool: worker-arm
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: openebs
        pool: worker-arm
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: openebs-worker-a
      clusterName: openebs
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: PacketMachineTemplate
        name: openebs-worker-arm
      version: v1.20.0
