init:
	#!/usr/bin/env sh
	read -p "API Key: " -s PACKET_API_KEY && export PACKET_API_KEY=${PACKET_API_KEY}
	clusterctl init --infrastructure packet

config:
	#!/usr/bin/env sh
	read -p "Project ID: " PROJECT_ID && export PROJECT_ID=${PROJECT_ID}
	source ./env
	clusterctl config cluster openebs \
		--kubernetes-version v1.20.0 \
		--control-plane-machine-count=1 \
		--worker-machine-count=3 \
		> cluster.yaml

cilium-repo:
	helm repo add cilium https://helm.cilium.io
	kubectl --kubeconfig=./kubeconfig create ns cilium

cilium:
	helm template cilium/cilium  \
		--version 1.8.5 \
		--namespace cilium \
		--set image.repository=docker.io/cilium/cilium \
		--set global.ipam.mode=cluster-pool \
		--set global.ipam.operator.clusterPoolIPv4PodCIDR=192.168.0.0/16 \
		--set global.ipam.operator.clusterPoolIPv4MaskSize=23 \
		--set global.nativeRoutingCIDR=192.168.0.0/16 \
		--set global.endpointRoutes.enabled=true \
		--set global.hubble.relay.enabled=true \
		--set global.hubble.enabled=true \
		--set global.hubble.listenAddress=":4244" \
		--set global.hubble.ui.enabled=true \
		> cilium.yaml
	kubectl --kubeconfig=./kubeconfig apply -f cilium.yaml

calico:
	kubectl --kubeconfig=./kubeconfig apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml

apply:
	kubectl apply -f cluster.yaml
	
kubeconfig:
	clusterctl get kubeconfig openebs > kubeconfig

openebs:
	kubectl --kubeconfig=./kubeconfig get nodes | awk '/worker/ {print $1}' | while read i; do kubectl --kubeconfig=./kubeconfig label node --overwrite=true $i openebs.io/engine=mayastor; done
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/namespace.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/moac-rbac.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/csi/moac/crds/mayastorpool.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/nats-deployment.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/csi-daemonset.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/moac-deployment.yaml
	kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/openebs/Mayastor/master/deploy/mayastor-daemonset.yaml

openebs-pool:
	#!/usr/bin/env bash
	set -euxo pipefail
	kubectl --kubeconfig=./kubeconfig get nodes | awk '/worker/ {print $1}' | while read i;
	do
		cat <<EOF | kubectl --kubeconfig=./kubeconfig apply -f -
	apiVersion: "openebs.io/v1alpha1"
	kind: MayastorPool
	metadata:
	  name: pool-${i}
	  namespace: mayastor
	spec:
	  node: ${i}
	  disks: ["/dev/sda", "/dev/sdb", "/dev/sdc"]
	EOF
	done

	cat <<EOF | kubectl --kubeconfig=./kubeconfig apply -f -
	kind: StorageClass
	apiVersion: storage.k8s.io/v1
	metadata:
	  name: mayastor-nvmf
	parameters:
	  repl: '3'
	  protocol: 'nvmf'
	provisioner: io.openebs.csi-mayastor
	EOF
